AWSTemplateFormatVersion: '2010-09-09'
Description: Network Infrastructure for MediaRelay
Transform: AWS::Serverless-2016-10-31

Parameters:
  AppId:
    Type: String
    Description: Application ID
  Environment:
    Type: String
    Default: Production
    AllowedValues:
      - Development
      - Staging
      - Production
  TransportStorage:
    Type: String
    Description: Transport Storage Bucket Name
  ContentStorage:
    Type: String
    Description: Content Storage Bucket Name

Resources:
  # VPC
  WorkerVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-vpc
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref AppId

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-igw
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref AppId

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref WorkerVPC
      InternetGatewayId: !Ref InternetGateway

  # Public Subnet
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref WorkerVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-public-subnet
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref AppId

  # Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref WorkerVPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-public-rt
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref AppId

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # Security Group
  WorkerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Fargate workers
      VpcId: !Ref WorkerVPC
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-worker-sg
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref AppId

  # VPC Endpoints
  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcId: !Ref WorkerVPC
      RouteTableIds:
        - !Ref PublicRouteTable
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource:
              - !Sub arn:aws:s3:::${TransportStorage}/*
              - !Sub arn:aws:s3:::${ContentStorage}/*
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-s3-endpoint
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref AppId

  DynamoDBEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub com.amazonaws.${AWS::Region}.dynamodb
      VpcId: !Ref WorkerVPC
      RouteTableIds:
        - !Ref PublicRouteTable
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-dynamodb-endpoint
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref AppId

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref WorkerVPC
    Export:
      Name: !Sub ${AWS::StackName}-VpcId

  SubnetId:
    Description: Public Subnet ID
    Value: !Ref PublicSubnet
    Export:
      Name: !Sub ${AWS::StackName}-SubnetId

  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref WorkerSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-SecurityGroupId

  PublicRouteTableId:
    Description: Public Route Table ID
    Value: !Ref PublicRouteTable
    Export:
      Name: !Sub ${AWS::StackName}-PublicRouteTableId

  S3EndpointId:
    Description: S3 VPC Endpoint ID
    Value: !Ref S3Endpoint
    Export:
      Name: !Sub ${AWS::StackName}-S3EndpointId

  DynamoDBEndpointId:
    Description: DynamoDB VPC Endpoint ID
    Value: !Ref DynamoDBEndpoint
    Export:
      Name: !Sub ${AWS::StackName}-DynamoDBEndpointId