version: 0.2
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      #- npm run test
  build:
    commands:
      #- npx tsc
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
  post_build:
    commands:
      #- npm prune --omit=dev
artifacts:
  files:
    - template-export.yml
